### ISSUE TITLE
Expand each TODO comment into a fully-described issue

### ISSUE THREAD

**Issue by daboross** [daboross/screeps-rs#4]
There are currently a ton of tasks documented only as "TODO" comments in the source code, or aren't documented at all. Expanding each of these into a github issue would make them much more approachable and hopefully provide some easy tasks to get started on.

Here, an issue of TODOs to turn into issues!

[diskcache.rs](https://github.com/daboross/screeps-rs/blob/master/networking/src/diskcache.rs):

- [x] TODO: Separate disk cache per server connection/IP
- [ ] TODO: Find errors that occur when rocksdb database is corrupted, and handle them

[event.rs](https://github.com/daboross/screeps-rs/blob/master/networking/src/event.rs)

- [ ] TODO: Move MapCacheData into a more appropriate file in the `memcache/` module
- [ ] TODO: Should we ever re-fetch terrain that's cached in memory, or ever invalidate it?
- [ ] TODO: Invalidate / remove old map view data that will eventually hog up memory if scrolling over map too much
- [ ] TODO: Keep track of more than one 'room detail' room, preferably with a 'last updated' in-game tick, or less preferably 'last updated' datetime.
- [ ] TODO: Keep the last 10 ticks of each subscribed room in memory for an 'instant replay' functionality

[memory.rs](https://github.com/daboross/screeps-rs/blob/master/networking/src/memcache/memory.rs)

- [ ] TODO: Handle "unknown" room objects better - things that have failed to parse. Ideally, these should be kept as an "unknown" object in the room data, and be displayable as a question mark w/ raw JSON data on hover-over.

[ws.rs](https://github.com/daboross/screeps-rs/blob/master/networking/src/tokio/ws.rs)

- [ ] TODO: Keep track of how long websocket connections stay open, and close+reconnect after a long period with no updates

[tokio.rs](https://github.com/daboross/screeps-rs/blob/master/networking/src/tokio/mod.rs)

- [ ] TODO: Create a way to propagate new login information to each HTTP executor/worker - currently login info is only propagated when worker pool starts up (first connection attempt).
- [ ] TODO: Re-initialize cache when it fails to load, rather than panicking and crashing application
- [ ] TODO: Figure out a good way to retrieve panic information from a separate thread that's started then completely left alone besides communication channels - so we can report this as an error to the user.

[memcache.rs](https://github.com/daboross/screeps-rs/blob/master/networking/src/memcache/mod.rs)

- [ ] TODO: Split 'room view error' out into it's own `enum` with specific variants for each type of error which store data, rather than a blanket string which contains all data directly inline, and requires allocation each error.

[tokio/utils.rs](https://github.com/daboross/screeps-rs/blob/master/networking/src/tokio/utils.rs)

- [ ] TODO: prevent an infinite loop within this recursive future

[ui/room_view.rs](https://github.com/daboross/screeps-rs/blob/master/src/rust/app/ui/room_view.rs)

- [ ] TODO: a "notification panel" on the right side of the screen which can display error events.

[rendering/map_view.rs](https://github.com/daboross/screeps-rs/blob/master/src/rust/app/ui/rendering/map_view.rs)

- [ ] TODO: Find a way to cache a full image for each room's terrain, so we aren't redrawing a box for each square each time the UI changes. This, if done correctly, would greatly speed up our rendering.
- [ ] TODO: Differentiate between natural terrain walls and player-made walls in map view.
- [ ] TODO: Differentiate between hostile and friendly users in map view.
